#!/bin/bash

# Install yay 
if  ! which yay; then
    sudo pacman -S --noconfirm base-devel
    git clone https://aur.archlinux.org/yay.git
    cd yay
    makepkg --noconfirm -si
    cd ../
    rm -rf yay
fi

yay --noconfirm

# install dependencies
yay -S --noconfirm hyprland pipewire-jack gnu-free-fonts neovim btop keepassxc \
    firefox-developer-edition stow wl-clipboard pipx ttf-firacode-nerd jq \
    pipewire-jack waybar vlc speech-dispatcher zsh eza bat zoxide alsa-tools \
    xdg-desktop-portal-hyprland rofi-wayland wlroots brightnessctl hypapper \
    cmake grim slurp luarocks python-pynvim hyprcwd nodejs npm sqlite


# yay -Rns --noconfirm nano-syntax-highlitghing nano

# 5  extra/virtualbox                   7.0.20-1             -> 7.1.2-1
#  4  extra/virtualbox-host-dkms         7.0.20-1             -> 7.1.2-1

# chsh azevedo (vai pedir o password) (/bin/zsh)
# append ZVM_VI_INSERT_ESCAPE_BINDKEY=jk in /home/azevedo/.local/share/zinit/plugins/jeffreytse---zsh-vi-mode
