#!/bin/bash

# configure yay 
if  ! which yay; then
    sudo pacman -S --noconfirm base-devel
    git clone https://aur.archlinux.org/yay.git
    cd yay
    makepkg --noconfirm -si
    cd ../
    rm -rf yay
fi

yay --noconfirm

# install dependencies
yay -S --noconfirm hyprland pipewire-jack gnu-free-fonts neovim \
    firefox-developer-edition stow wl-clipboard pipx ttf-firacode-nerd \
    pipewire-jack waybar vlc speech-dispatcher zsh eza bat zoxide \
    xdg-desktop-portal-hyprland rofi-wayland wlroots brightnessctl


# chsh azevedo (vai pedir o password) (/bin/zsh)
# append ZVM_VI_INSERT_ESCAPE_BINDKEY=jk in /home/azevedo/.local/share/zinit/plugins/jeffreytse---zsh-vi-mode
