continuation_prompt = ' ▶ '

[git_status]
format = '$ahead_behind$conflicted$stashed$staged$modified'
conflicted = '[~$count](bold red) '
stashed = '[*$count] '
staged = '[+$count](blue) '
modified = '[?$count](yellow) '

ahead = '[⇡${count}](bold green) '
diverged = '⇕⇡${ahead_count}⇣${behind_count} '
behind = '⇣${count} '


[username]
format = '[ 󰣇 ](bold blue)'
show_always = true

[directory]
read_only = ' 󰦝 '
read_only_style = 'cyan'

[character]
success_symbol = '[ ❯](bold green)'
error_symbol = '[ ❯](bold red)'
